EWPP-2375: Add Luxembourgish string translations.
openeuropa/oe_corporate_blocks pull request #114
Opened 2022-06-29 13:12 UTC by 22Alexandra

2022-07-01 10:47 UTC, sergepavle requested changes
Seems like missed translation of the following string: European Data Protection Board

2022-07-01 12:42 UTC, sergepavle submitted a review, later dismissed

2022-07-05 08:34 UTC, imanoleguskiza approved these changes, later dismissed

2022-07-26 10:02 UTC, sergepavle approved these changes

2022-07-26 10:03 UTC, imanoleguskiza approved these changes

2022-07-26 10:05 UTC, merged