OEL-3058: Check strings before deletion.
openeuropa/oe_corporate_blocks pull request #159
Opened 2024-06-19 08:25 UTC by drishu

## OEL-3058

### Description

Websites other than ewpp may not have the strings, so when the local storage tries to fetch them the result will be null.

reported also in https://github.com/openeuropa/oe_corporate_blocks/issues/158

### Change log

- Fixed: oe_corporate_blocks_post_update_40010

2024-06-19 14:30 UTC, brummbar requested changes

2024-06-19 14:30 UTC, brummbar commented on oe_corporate_blocks.post_update.php
> +    ];
The 'source' key can be dropped and we keep just the value.

2024-06-20 07:11 UTC, drishu commented on oe_corporate_blocks.post_update.php
> +    ];
Not if we use StringDatabaseStorage, the keys of the arrays must match fields in the db table (lid, source, context, version), and it must be an array of conditions.

2024-06-20 14:54 UTC, brummbar commented on oe_corporate_blocks.post_update.php
> +    ];
```suggestion
    $strings = [
      'Search all EU institutions and bodies',
      'EU institutions and bodies',
      'https://european-union.europa.eu/institutions-law-budget/institutions-and-bodies/search-all-eu-institutions-and-bodies_en',
    ];
```
and then
```
$string = $storage->findString(['source' => $string]);

2024-06-20 14:55 UTC, brummbar commented on oe_corporate_blocks.post_update.php
> +    ];
Let's also take the chance to rename $strings to $sources.

2024-06-21 06:40 UTC, drishu commented on oe_corporate_blocks.post_update.php
> +    ];
clear enough, I misunderstood the first time

2024-06-24 14:29 UTC, brummbar approved these changes

2024-06-24 14:42 UTC, nagyad approved these changes

2024-06-24 14:42 UTC, merged