OPENEUROPA-2340: Implement site specific footer.
openeuropa/oe_corporate_blocks pull request #28
Opened 2019-10-21 14:16 UTC by sergepavle

## OPENEUROPA-2340

### Description

The scope of this ticket is to implement the site specific footer as outlined in OPENEUROPA-2339.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-10-25 12:02 UTC, imanoleguskiza requested changes

2019-10-25 12:44 UTC, imanoleguskiza requested changes

2019-10-25 12:44 UTC, imanoleguskiza commented on templates/oe-corporate-blocks-footer.html.twig
> +      <p class="footer__custom-label">Follow us:</p>
This needs to be translatable.

2019-10-28 11:02 UTC, sergepavle commented on tests/Behat/CorporateBlocksContext.php
> +   * @Then Links in the :region region do not contains the links:
it is modified this step: `@Then Links in the :region region contains the links:`. See: `\Drupal\Tests\oe_corporate_blocks\Behat\CorporateBlocksContext::assertCorporateBlockLinksUrls`. Should I rename also this one?

2019-10-28 11:04 UTC, sergepavle commented on src/Plugin/Block/FooterBlock.php
> +          $link['social_network'] = $link_entity->getSocialNetwork();
Sorry, I didn't get what is the alternative approach?

2019-10-28 14:28 UTC, imanoleguskiza approved these changes

2019-11-19 12:27 UTC, ademarco commented
We won't provide this functionality on 1.x version. Closing.

2019-11-19 12:27 UTC, closed without merging