OPENEUROPA-2630: Remove item from EU corporate footer.
openeuropa/oe_corporate_blocks pull request #43
Opened 2019-12-09 15:14 UTC by sergepavle

## OPENEUROPA-2630

### Description

Please remove the "Presidency of the Council of the EU" link from EU version of the corporate footer.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-12-10 08:06 UTC, nagyad requested changes

2019-12-10 08:06 UTC, nagyad commented on oe_corporate_blocks.post_update.php
> + * Remove 'Presidency of the Council of the EU' inside UE footer.
Remove 'Presidency of the Council of the EU' from EU footer.

2019-12-10 08:06 UTC, nagyad commented on oe_corporate_blocks.post_update.php
> +      $link['href'] === 'https://www.romania2019.eu/home/') {
Please fix the indentation.

2019-12-10 08:06 UTC, nagyad commented on tests/features/corporate-blocks.feature
> +@api @footer
Do we need this tag?

2019-12-10 09:29 UTC, nagyad approved these changes

2019-12-11 11:47 UTC, imanoleguskiza approved these changes

2019-12-11 13:01 UTC, merged