OPENEUROPA-2632: Add more social link options in FooterLinkSocial.
openeuropa/oe_corporate_blocks pull request #44
Opened 2019-12-12 16:01 UTC by dxvargas

## OPENEUROPA-2632: Add more social link options in FooterLinkSocial

### Description

OPENEUROPA-2632: Add more social link options in FooterLinkSocial. Full list should be:

- Facebook
- Instagram
- Linkedin
- Pinterest
- RSS
- Skype
- Twitter
- YouTube

2019-12-13 09:52 UTC, sergepavle approved these changes

2019-12-13 10:14 UTC, sergepavle requested changes
I think we need extend little bit tests for adding checking that we have required options.
It will be enough 1 step with checking allowed social networks in backend.

2019-12-13 14:04 UTC, dxvargas commented
@sergepavle tests were added

2019-12-13 14:16 UTC, sergepavle approved these changes
Thank you for updates. Looks good!

2019-12-16 07:22 UTC, nagyad approved these changes

2019-12-16 07:22 UTC, merged