EWPP-467: Add footer link sections
openeuropa/oe_corporate_blocks pull request #61
Opened 2020-11-10 14:42 UTC by ademarco

2020-11-18 10:03 UTC, imanoleguskiza requested changes

2020-11-18 10:03 UTC, imanoleguskiza commented on src/Entity/FooterLinkSection.php
> + *       "delete" = "Drupal\oe_corporate_blocks\Form\FooterLinkGeneralDeleteForm"
The problem with using the same cancel form as the links is that on cancelling we will be redirected to the link collection page and not the section collection page.

2020-11-18 10:03 UTC, imanoleguskiza commented on oe_corporate_blocks.post_update.php
> +  $general_links = \Drupal::entityTypeManager()->getStorage('footer_link_general')->loadMultiple();
I am wondering if there is any value on doing this in a batch process.

2020-11-18 10:03 UTC, imanoleguskiza commented on src/Form/FooterLinkSectionForm.php
> +      '#value' => $this->t('weight') ?? 0,
I believe this should be $section->getWeight() ?? 0

2020-11-18 10:03 UTC, imanoleguskiza commented on tests/src/Functional/FooterLinkManagementTest.php
> +    // Assert new weight when saving the overview page.
It feels like we are missing some steps here to change the weight prior to asserting the weight again.

2020-11-18 10:03 UTC, imanoleguskiza commented on tests/src/Traits/AssertFooterLinksTrait.php
> +    $this->assertEqual($link->getUrl()->toString(), $url, "'{$label}' URL was expected to be set to '{$url}', but '{$link->getUrl()->toString()}' was found.");
Usually we use assertEquals where we can put the expected value first.

2020-11-20 13:37 UTC, ademarco commented on src/Entity/FooterLinkSection.php
> + *       "delete" = "Drupal\oe_corporate_blocks\Form\FooterLinkGeneralDeleteForm"
Yeah, good one, I'll fix this in this PR.

2020-11-20 13:38 UTC, ademarco commented on oe_corporate_blocks.post_update.php
> +  $general_links = \Drupal::entityTypeManager()->getStorage('footer_link_general')->loadMultiple();
Nah, there can't be more than 10-20 links per site anyway, we can handle 100s of entities without any batch.

2020-11-20 13:55 UTC, ademarco commented on tests/src/Functional/FooterLinkManagementTest.php
> +    // Assert new weight when saving the overview page.
Right, it was a leftover from a previous test.

2020-11-20 13:56 UTC, ademarco commented on tests/src/Traits/AssertFooterLinksTrait.php
> +    $this->assertEqual($link->getUrl()->toString(), $url, "'{$label}' URL was expected to be set to '{$url}', but '{$link->getUrl()->toString()}' was found.");
The method's signature seems not to agree with that :smile: 
```
  protected function assertEqual($actual, $expected, $message = '') {
```

2020-11-20 14:09 UTC, ademarco commented on src/Form/FooterLinkSectionForm.php
> +      '#value' => $this->t('weight') ?? 0,
I'm a bad person.

2020-11-20 14:58 UTC, 22Alexandra approved these changes

2020-11-23 07:31 UTC, imanoleguskiza approved these changes

2020-11-23 07:58 UTC, merged