EWPP-468: Add sections to site_specific_footer.
openeuropa/oe_corporate_blocks pull request #64
Opened 2020-11-24 12:57 UTC by drishu

## EWPP-468

### Description

[Insert description here]

### Change log

- Added:
- Changed:
   - adapt FooterBlockBase to sections.
   - split getSiteSpecificFooterLinks into 2 new methods.
   - adapt templates to sections.

2020-11-25 11:36 UTC, ademarco requested changes

2020-11-25 11:36 UTC, ademarco commented on src/FooterLinkManager.php
> +  }
Let's remove this form here, it's not this service's scope to return cache tags of two entity type storage.

2020-11-25 11:36 UTC, ademarco commented on src/FooterLinkManagerInterface.php
> +  public function getListCacheTags(): array;
Let's remove this form here, it's not this service's scope to return cache tags of two entity type storage.

2020-11-25 11:36 UTC, ademarco commented on src/FooterLinkManager.php
> +  }
Also mind the way tags should be merged, it's not done with an array merge, Drupal offers a service method for that.

2020-11-25 11:36 UTC, ademarco commented on src/Plugin/Block/FooterBlockBase.php
> +    $cache->addCacheTags($this->linkManager->getListCacheTags());
Simple add entity type cache tags from the different storages here by calling `addCacheTags` twice, as done below in getSocialFooterLinks().

2020-11-25 13:37 UTC, ademarco requested changes

2020-11-25 13:37 UTC, ademarco commented on src/Plugin/Block/FooterBlockBase.php
> +    foreach ($this->linkManager->getSections() as $section) {
Let's only return sections with links.

2020-11-26 14:15 UTC, 22Alexandra approved these changes

2020-11-27 09:30 UTC, ademarco approved these changes

2020-11-27 09:30 UTC, merged