EWPP-1065: Add links to EU footer.
openeuropa/oe_corporate_blocks pull request #88
Opened 2021-04-28 15:24 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-04-29 12:35 UTC, 22Alexandra commented on oe_corporate_blocks.post_update.php
> + * Import updated EU footer data, along with their translations.
Only updates the data, the translations have to be imported manually.
```suggestion
 * Updates EU footer data.
```

2021-04-29 12:39 UTC, 22Alexandra submitted a review, later dismissed

2021-04-29 12:51 UTC, 22Alexandra submitted a review, later dismissed

2021-04-30 07:12 UTC, upchuk requested changes

2021-04-30 07:12 UTC, upchuk commented on oe_corporate_blocks.post_update.php
> +    if ($data = $source->read($config)) {
Why was this necessary?

1. Why wouldn't there be data for a config name?
2. If there isn't data, shouldn't we fail it so we know there was no data there when there should have been? Otherwise we don;t know what's going on

2021-04-30 07:12 UTC, upchuk commented on translations/oe_corporate_blocks-pt-pt.po
> +msgstr "https://epso.europa.eu/home_pt"
This site uses pt_pt...so we have to put that for the moment.

2021-04-30 09:03 UTC, upchuk approved these changes, later dismissed

2021-04-30 10:26 UTC, upchuk commented on oe_corporate_blocks.post_update.php
> +    if ($data = $source->read($config)) {
Understood, it's fine

2021-05-03 14:50 UTC, upchuk approved these changes

2021-05-03 14:50 UTC, 22Alexandra approved these changes

2021-05-03 14:50 UTC, merged