OEL-73: Drupal 9 compatibility fixes.
openeuropa/oe_corporate_blocks pull request #90
Opened 2021-06-03 15:25 UTC by saidatom

2021-06-07 15:16 UTC, nagyad submitted a review, later dismissed

2021-06-18 11:36 UTC, brummbar requested changes
Blocked by another module update.

2021-07-01 08:43 UTC, brummbar approved these changes

2021-07-01 08:55 UTC, upchuk approved these changes

2021-07-01 08:55 UTC, merged